### ISSUE TITLE
Stripe library is missing

### ISSUE THREAD

**Issue by qasim-rafique** [thelia-modules/StripePayment#5]
Hi there, i have installed StripePayment mudule in  thelia and also add stripe library folder in  <thelia-root>/ core/ vendor 
and then trying to activate the module from admin panel but i am getting error "Stripe library is missing"

Please help me to fix this

**Comment by Mertiozys** [comment]
Hi,
Can you tell us how you installed the module ? Manually or with composer ?
If you did it manually, please try tu run `composer dumpautoload` to index the library

**Comment by qasim-rafique** [comment]
yeah i did it Manually. but in which folder i should run this command?

**Comment by Mertiozys** [comment]
In your project folder

**Comment by qasim-rafique** [comment]
i did it, it gave me message generating auto-load file  and now giving me same error

**Comment by Mertiozys** [comment]
Hum ... what about removing the module folder and re-installing it with the composer command `composer require thelia/stripe-payment-module:~1.0` ?

**Comment by qasim-rafique** [comment]
thanks bro its working with composer, but  what's wrong with Manual?

**Comment by Mertiozys** [comment]
Maybe the path of the library, depending on the Thelia you're using (thelia/thelia or thelia/thelia-project).
Satisfied to have helped you :)
